# SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)

USER_TARGETS   := udptime_user
BPF_TARGETS    := udptime_kern

#LDLIBS     += -pthread
EXTRA_DEPS += udptime.h

LIB_DIR = ../lib

include $(LIB_DIR)/common.mk
